#!/bin/bash

LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libgomp.so.1 python defense.py --lr 0.01 --batch_size 8 --epochs 10 -r --tau 0.1 --num_steps 500000 --test_size=1 --num_completions 5000 --initial_exploration 3000 --alpha 1. --beta 1.