#!/bin/bash


#python run_gdm.py --test_size 1 --evaluate_every 1 -r --save
python run_gdm.py --test_size 5 --evaluate_every 1 -r --save
python run_gdm.py --test_size 10 --evaluate_every 1 -r --save
python run_gdm.py --evaluate_every 1 -r --save